#+TITLE: TScript34 P0019

** Goal

An embeddable, general-purpose TS34 interpreter,
possibly with support for alternate, PostScript-like syntax.

Intended primary use cases:
- Horsing with RDF structures, especially TOGVM expressions
- Serve as a protocol for scripting and communication between
  random programs like ContentCouch that seem to
  "want to have a simple scripting language"

The VM design seems a good one, as it allows side-effects
to be handled orthogonally to interpretation.
I want the core interpreter logic to be 100% pure functional.

The 'single-class' concept has been proved well enough;
I can back down on that.  Though it may still be wise
to choose fewer instad of more classes.  I haven't quite
figured out how to balance my approach.  Java makes it difficult, I think.

** Origins

See WSITEM-3408 p155.

Based on P0009, which was in turn based on P0006.
"This one I can pollute."

First step was to split P0006 and P0009 subtrees,
so that this could be a nice self-contained tree,
which is what I decided is the way to go for new
sub-projects.

Git commits:

| original p0009-master                   | 248d236ebf20600249d7a26125aa0eaeeeb09480 |
| subtrees/p0006/split-from-master        | 891e25d0bc32d6558a5026c1e6a6dac969c93f8a |
| subtrees/p0009/split+rebased-onto-p0006 | 62c68e7c1422a849bb54b09c2fdba76bc042d038 |
